import cssfuck.chars as chars
def compile(text):
    text = text.replace(chars.a, "a")
    text = text.replace(chars.b, "b")
    text = text.replace(chars.c, "c")
    text = text.replace(chars.d, "d")
    text = text.replace(chars.e, "e")
    text = text.replace(chars.f, "f")
    text = text.replace(chars.g, "g")
    text = text.replace(chars.h, "h")
    text = text.replace(chars.i, "i")
    text = text.replace(chars.j, "j")
    text = text.replace(chars.k, "k")
    text = text.replace(chars.l, "l")
    text = text.replace(chars.m, "m")
    text = text.replace(chars.n, "n")
    text = text.replace(chars.o, "o")
    text = text.replace(chars.p, "p")
    text = text.replace(chars.q, "q")
    text = text.replace(chars.r, "r")
    text = text.replace(chars.s, "s")
    text = text.replace(chars.t, "t")
    text = text.replace(chars.u, "u")
    text = text.replace(chars.v, "v")
    text = text.replace(chars.w, "w")
    text = text.replace(chars.x, "x")
    text = text.replace(chars.y, "y")
    text = text.replace(chars.z, "z")
    return text
def decompile(text):
    text = text.replace("a",chars.a)
    text = text.replace("b",chars.b)
    text = text.replace("c",chars.c)
    text = text.replace("d",chars.d)
    text = text.replace("e",chars.e)
    text = text.replace("f",chars.f)
    text = text.replace("g",chars.g)
    text = text.replace("h",chars.h)
    text = text.replace("i",chars.i)
    text = text.replace("j",chars.j)
    text = text.replace("k",chars.k)
    text = text.replace("l",chars.l)
    text = text.replace("m",chars.m)
    text = text.replace("n",chars.n)
    text = text.replace("o",chars.o)
    text = text.replace("p",chars.p)
    text = text.replace("q",chars.q)
    text = text.replace("r",chars.r)
    text = text.replace("s",chars.s)
    text = text.replace("t",chars.t)
    text = text.replace("u",chars.u)
    text = text.replace("v",chars.v)
    text = text.replace("w",chars.w)
    text = text.replace("x",chars.x)
    text = text.replace("y",chars.y)
    text = text.replace("z",chars.z)
    return text